!!dev.wuffs.squatgrow.config.SquatGrowConfig
allowAdventureTwerking: false
chance: 0.5
debug: false
enableMysticalCrops: true
ignoreList: ['minecraft:grass_block', 'minecraft:grass', 'minecraft:tall_grass', 'minecraft:netherrack',
  'minecraft:warped_nylium', 'minecraft:crimson_nylium', '#minecraft:crops', 'immersiveengineering:hemp',
  'minecraft:kelp', 'minecraft:kelp_plant', 'minecraft:moss_block', 'minecraft:crimson_nylium',
  '#ftbstoneblock:squatgrow_blacklist']
range: 3
useWhitelist: false
